// Packs this Lumina plugin for the Lumina Marketplace.
//
//   dart run tool/pack_plugin.dart [<plugin dir>] [--out <dir>] [--dry-run]
//                                  [--verbose] [--skip-disallowed]
//
// (`dart tool/pack_plugin.dart ...` runs the same without pub's dependency
// resolution and build hooks, so it is faster in a plugin that depends on
// lumina.)
//
// Writes build/pack/<name>-<version>.zip (or <dir>/<name>-<version>.zip): the
// plugin folder under a single <name>/ top folder, without build outputs, tool
// folders, secrets and ignored files, ready for Publish -> Plugin -> Choose
// plugin .zip on the marketplace.
//
//   --out <dir>         write the zip to <dir> instead of build/pack/
//   --dry-run           list what would go in and what is left out; write nothing
//   --verbose           list every packed file
//   --skip-disallowed   leave out files the marketplace refuses (with a warning)
//                       instead of failing
//
// Always left out:
//   - .dart_tool/, .git/, .idea/, .vscode/, node_modules/ anywhere, and build/,
//     coverage/ at the plugin root;
//   - pubspec_overrides.yaml, .packages, .flutter-plugins*, *.part, *.tmp,
//     *.log, *.iml, *.swp, *~, .DS_Store, Thumbs.db, desktop.ini;
//   - secrets: .env*, credentials*.json.
// Also left out: whatever the .gitignore files ignore (root and nested); a
// folder's .pubignore replaces its .gitignore, as `dart pub publish` does, to
// leave out more (test/, doc/, ...).
//
// Checked (exit code 2 on an error, every problem named): the <name>.lmplugin
// manifest (name, a marketplace X.Y.Z version, both equal to pubspec.yaml's),
// the LICENSE file behind a declared "license", the changelog's section for
// the version, and every file against the marketplace's allow-list.
//
// Generated by Lumina (kPluginPackScript in lumina's
// lib/data/services/plugin_pack_script.dart). It uses dart: libraries only, so
// it runs in every plugin, content-only ones without a pubspec.yaml included.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

/// Folder names left out wherever they are.
const _excludedFolders = {'.dart_tool', '.git', '.idea', '.vscode', 'node_modules', '.svn', '.hg'};

/// Folder names left out at the plugin root.
const _excludedRootFolders = {'build', 'coverage'};

/// File names (lower case) left out wherever they are.
const _excludedFiles = {
  'pubspec_overrides.yaml', '.packages', '.flutter-plugins', '.flutter-plugins-dependencies', //
  '.ds_store', 'thumbs.db', 'desktop.ini',
};

/// File name suffixes left out wherever they are (downloads, logs, editors).
const _excludedSuffixes = {'.part', '.tmp', '.log', '.iml', '.swp', '~'};

/// Secrets, never packed even when a .gitignore forgets them.
bool _isSecret(String lowerName) =>
    lowerName.startsWith('.env') || (lowerName.startsWith('credentials') && lowerName.endsWith('.json'));

// What the marketplace accepts in a plugin upload (lumina_marketplace
// server/lib/src/storage/zip_validator.dart); keep in step with it.
// marketplace-allow-list:start
const _allowedExtensions = {
  'glb', 'gltf', 'bin', 'obj', 'mtl', 'fbx', 'dae', 'lmas', 'filamesh', //
  'png', 'jpg', 'jpeg', 'tga', 'webp', 'ktx', 'ktx2', 'hdr', 'exr', 'svg',
  'wav', 'ogg', 'mp3', 'flac', 'ttf', 'otf',
  'dart', 'c', 'cc', 'cpp', 'h', 'hpp', 'js', 'glsl', 'vert', 'frag', 'comp', 'mat',
  'json', 'yaml', 'yml', 'md', 'txt', 'lmproject', 'lmplugin', 'csv', 'lock',
};
const _allowedBareNames = {'license', 'licence', 'readme', 'notice', 'changelog', 'copying', 'authors'};
const _allowedDotNames = {'.gitignore', '.gitattributes', '.metadata', '.pubignore'};
// marketplace-allow-list:end

/// Root license texts the marketplace reads (lower case).
const _licenseFileNames = {'license', 'license.md', 'license.txt', 'licence', 'copying', 'copying.md', 'copying.txt'};

/// The marketplace's default upload limit and entry limit.
const _maxUploadBytes = 256 * 1024 * 1024;
const _maxEntries = 10000;

/// Every entry is dated 2000-01-01 00:00, so unchanged sources pack to the
/// same bytes.
const _dosTime = 0;
const _dosDate = (20 << 9) | (1 << 5) | 1;

final _packageName = RegExp(r'^[a-z][a-z0-9_]*$');
final _marketVersion = RegExp(r'^\d{1,4}\.\d{1,4}\.\d{1,4}$');
const _usage = 'Usage: dart run tool/pack_plugin.dart [<plugin dir>] [--out <dir>] [--dry-run] [--verbose] '
    '[--skip-disallowed]';

Future<void> main(List<String> args) async {
  String? outArg;
  String? dirArg;
  var dryRun = false;
  var verbose = false;
  var skipDisallowed = false;
  for (var i = 0; i < args.length; i++) {
    final a = args[i];
    if ((a == '--out' || a == '-o') && i + 1 < args.length) {
      outArg = args[++i];
    } else if (a.startsWith('--out=')) {
      outArg = a.substring('--out='.length);
    } else if (a == '--dry-run' || a == '-n') {
      dryRun = true;
    } else if (a == '--verbose' || a == '-v') {
      verbose = true;
    } else if (a == '--skip-disallowed') {
      skipDisallowed = true;
    } else if (a == '--help' || a == '-h') {
      stdout.writeln(_usage);
      return;
    } else if (!a.startsWith('-') && dirArg == null) {
      dirArg = a;
    } else {
      stderr.writeln('Unknown argument: $a\n$_usage');
      exitCode = 64;
      return;
    }
  }

  final root = dirArg != null ? Directory(_native(Directory(dirArg).absolute.path)) : _pluginRoot();
  if (root == null || !root.existsSync()) {
    stderr.writeln('No plugin folder: run this in a folder that holds a <name>.lmplugin manifest.');
    exitCode = 2;
    return;
  }

  // The manifest.
  final manifests = root
      .listSync(followLinks: false)
      .whereType<File>()
      .where((f) => _name(f.path).toLowerCase().endsWith('.lmplugin'))
      .toList();
  if (manifests.length != 1) {
    stderr.writeln('Not packed: ${root.path} needs exactly one <name>.lmplugin manifest; found ${manifests.length}.');
    exitCode = 2;
    return;
  }
  final manifestFile = manifests.single;
  final manifestName = _name(manifestFile.path);
  final basename = manifestName.substring(0, manifestName.length - '.lmplugin'.length);
  final problems = <String>[];
  final warnings = <String>[];
  Map<String, Object?> manifest;
  try {
    final decoded = jsonDecode(manifestFile.readAsStringSync());
    if (decoded is! Map) throw const FormatException('not a JSON object');
    manifest = decoded.cast<String, Object?>();
  } on Object catch (e) {
    stderr.writeln('Not packed: $manifestName is not a valid JSON manifest: $e');
    exitCode = 2;
    return;
  }
  final name = manifest['name'];
  final version = manifest['version'];
  if (name is! String || !_packageName.hasMatch(name)) {
    problems.add('$manifestName: "name" ${jsonEncode(name)} is not a Dart package name '
        '(lowercase letters, digits and _, starting with a letter)');
  } else if (name != basename) {
    problems.add('$manifestName: "name" "$name" does not match the file name ($basename.lmplugin)');
  }
  if (version is! String || !_marketVersion.hasMatch(version)) {
    problems.add('$manifestName: "version" ${jsonEncode(version)} is not a marketplace version (X.Y.Z, e.g. 1.0.0)');
  }
  for (final key in const ['friendly_name', 'description', 'category', 'engine_version', 'license', 'changelog']) {
    if (manifest[key] != null && manifest[key] is! String) problems.add('$manifestName: "$key" is not a string');
  }
  final authors = manifest['authors'];
  if (authors != null && (authors is! List || authors.any((a) => a is! String))) {
    problems.add('$manifestName: "authors" is not a list of strings');
  }

  // pubspec.yaml (code plugins): the same name and version.
  final pubspec = File(_join(root.path, 'pubspec.yaml'));
  if (pubspec.existsSync()) {
    final text = pubspec.readAsStringSync();
    final pubName = _yamlScalar(text, 'name');
    final pubVersion = _yamlScalar(text, 'version');
    if (name is String && pubName != name) {
      problems.add('the name differs: $manifestName says "$name", pubspec.yaml says "${pubName ?? '(none)'}"');
    }
    if (version is String && pubVersion != version) {
      problems.add('the version differs: $manifestName says $version, pubspec.yaml says ${pubVersion ?? '(none)'}');
    }
  }

  // The license text behind a declared "license".
  final rootNames = {for (final e in root.listSync(followLinks: false)) if (e is File) _name(e.path).toLowerCase()};
  final license = manifest['license'];
  if (license is String && license.trim().isNotEmpty && !rootNames.any(_licenseFileNames.contains)) {
    problems.add('$manifestName: "license" declares $license, but the plugin has no LICENSE file with its text');
  }

  // The files.
  final outDir = outArg == null ? Directory(_join(root.path, 'build/pack')) : Directory(_native(Directory(outArg).absolute.path));
  final outName = '${name is String ? name : basename}-${version is String ? version : '0.0.0'}.zip';
  final outFile = File(_join(outDir.path, outName));
  final tmpFile = File('${outFile.path}.tmp');
  final files = <String>[];
  final leftOut = <String, int>{};
  final links = <String>[];
  _walk(root, '', const [], files, leftOut, links, skip: {_key(outFile.path), _key(tmpFile.path)});
  files.sort();

  final refused = <String>[
    for (final path in files)
      if (_refusal(path) case final reason?) '$path ($reason)',
    for (final path in links) '$path (a symbolic link; the marketplace takes regular files only)',
  ];
  if (refused.isNotEmpty && skipDisallowed) {
    files.removeWhere((path) => _refusal(path) != null);
    warnings.add('left out ${refused.length} file(s) the marketplace does not accept: ${refused.join(', ')}');
    refused.clear();
  }

  // The changelog: a section for the version (or Unreleased, with a warning).
  final declaredChangelog = manifest['changelog'];
  final changelogPath = declaredChangelog is String && declaredChangelog.trim().isNotEmpty
      ? declaredChangelog.trim().replaceAll(r'\', '/').replaceFirst(RegExp(r'^\./'), '')
      : files.where((f) => const {'changelog.md', 'changelog', 'changelog.txt'}.contains(f.toLowerCase())).firstOrNull;
  if (changelogPath != null) {
    final declared = declaredChangelog is String && declaredChangelog.trim().isNotEmpty;
    if (!files.contains(changelogPath)) {
      problems.add('$manifestName: "changelog" names $changelogPath, which is not in the pack');
    } else if (version is String) {
      final sections = [
        for (final line in File(_join(root.path, changelogPath)).readAsLinesSync())
          if (RegExp(r'^##\s+\[?v?([^\]\s]+)').firstMatch(line) case final m?) m.group(1)!.toLowerCase(),
      ];
      if (sections.contains(version)) {
        // The section the marketplace fills the release notes from.
      } else if (sections.contains('unreleased')) {
        warnings.add('$changelogPath has no "## $version" section; the marketplace shows "## Unreleased" instead');
      } else if (declared) {
        problems.add('$changelogPath (the manifest\'s "changelog") has no "## $version" or "## Unreleased" section');
      } else {
        warnings.add('$changelogPath has no "## $version" section; the release notes will be empty');
      }
    }
  }
  if (files.length > _maxEntries) problems.add('${files.length} files; the marketplace takes at most $_maxEntries');

  for (final w in warnings) {
    stderr.writeln('Warning: $w');
  }
  if (problems.isNotEmpty || refused.isNotEmpty) {
    stderr.writeln('Not packed: the marketplace would refuse this plugin.');
    for (final p in problems) {
      stderr.writeln('  - $p');
    }
    if (refused.isNotEmpty) {
      stderr.writeln('  Files the marketplace does not accept (delete them, list them in .gitignore / .pubignore, '
          'or pass --skip-disallowed):');
      for (final r in refused) {
        stderr.writeln('    $r');
      }
    }
    exitCode = 2;
    return;
  }

  final leftOutText = (leftOut.entries.toList()..sort((a, b) => a.key.compareTo(b.key)))
      .map((e) => e.key.endsWith('/') ? '${e.key} (${e.value} ${e.value == 1 ? 'file' : 'files'})' : e.key)
      .join(', ');
  if (dryRun || verbose) {
    for (final f in files) {
      stdout.writeln('  + $name/$f');
    }
  }
  if (dryRun) {
    stdout.writeln('Dry run: $name $version would pack ${files.length} files into ${outFile.path}; nothing written.');
    if (leftOutText.isNotEmpty) stdout.writeln('  Left out: $leftOutText');
    return;
  }

  // The archive: written to <zip>.tmp, then renamed.
  outDir.createSync(recursive: true);
  final unpacked = _writeZip(tmpFile, root, name as String, files);
  if (outFile.existsSync()) outFile.deleteSync();
  tmpFile.renameSync(outFile.path);
  final zipped = outFile.lengthSync();

  stdout.writeln('Packed $name $version for the Lumina Marketplace:');
  stdout.writeln('  ${outFile.path} - ${files.length} files - ${_size(zipped)} (${_size(unpacked)} unpacked)');
  if (leftOutText.isNotEmpty) stdout.writeln('  Left out: $leftOutText');
  if (zipped > _maxUploadBytes) {
    stdout.writeln("  Warning: larger than the marketplace's default ${_maxUploadBytes ~/ (1024 * 1024)} MB upload limit.");
  }
  stdout.writeln('Upload it on the Lumina Marketplace: Publish -> Plugin -> Choose plugin .zip.');
}

/// The plugin folder: the working directory when it holds a manifest, else
/// the folder above this script's tool/.
Directory? _pluginRoot() {
  bool hasManifest(Directory d) =>
      d.existsSync() && d.listSync(followLinks: false).any((e) => e is File && e.path.toLowerCase().endsWith('.lmplugin'));
  final cwd = Directory.current;
  if (hasManifest(cwd)) return cwd;
  final script = Platform.script;
  if (script.scheme == 'file') {
    final above = File.fromUri(script).parent.parent;
    if (hasManifest(above)) return above;
  }
  return null;
}

/// A top-level `key: value` of a pubspec, unquoted, or null.
String? _yamlScalar(String yaml, String key) {
  final m = RegExp('^$key:[ \\t]*([^#\\r\\n]*)', multiLine: true).firstMatch(yaml);
  if (m == null) return null;
  var v = m.group(1)!.trim();
  if (v.length >= 2 && (v.startsWith('"') && v.endsWith('"') || v.startsWith("'") && v.endsWith("'"))) {
    v = v.substring(1, v.length - 1);
  }
  return v.isEmpty ? null : v;
}

/// One ignore rule of a .gitignore / .pubignore in folder [base] ('' = root).
class _Rule {
  _Rule(this.base, this.regex, {required this.negated, required this.dirOnly, required this.anchored});
  final String base;
  final RegExp regex;
  final bool negated;
  final bool dirOnly;
  final bool anchored;

  /// Whether the rule matches [path] (plugin-relative).
  bool matches(String path, bool isDir) {
    if (dirOnly && !isDir) return false;
    if (base.isNotEmpty && !path.startsWith('$base/')) return false;
    final rel = base.isEmpty ? path : path.substring(base.length + 1);
    return regex.hasMatch(anchored ? rel : rel.split('/').last);
  }
}

List<_Rule> _parseIgnore(String text, String base) {
  final rules = <_Rule>[];
  for (var line in const LineSplitter().convert(text)) {
    if (line.trim().isEmpty || line.startsWith('#')) continue;
    line = line.trimRight();
    var negated = false;
    if (line.startsWith('!')) {
      negated = true;
      line = line.substring(1);
    } else if (line.startsWith(r'\')) {
      line = line.substring(1);
    }
    var dirOnly = false;
    if (line.endsWith('/')) {
      dirOnly = true;
      line = line.substring(0, line.length - 1);
    }
    if (line.isEmpty) continue;
    final anchored = line.contains('/');
    if (line.startsWith('/')) line = line.substring(1);
    rules.add(_Rule(base, RegExp('^${_globToRegex(line)}\$'), negated: negated, dirOnly: dirOnly, anchored: anchored));
  }
  return rules;
}

String _globToRegex(String glob) {
  final b = StringBuffer();
  for (var i = 0; i < glob.length; i++) {
    final c = glob[i];
    if (c == '*') {
      if (i + 1 < glob.length && glob[i + 1] == '*') {
        final slash = i + 2 < glob.length && glob[i + 2] == '/';
        b.write(slash ? '(?:.*/)?' : '.*');
        i += slash ? 2 : 1;
      } else {
        b.write('[^/]*');
      }
    } else if (c == '?') {
      b.write('[^/]');
    } else if (c == '[') {
      final end = glob.indexOf(']', i + 1);
      if (end < 0) {
        b.write(r'\[');
      } else {
        var cls = glob.substring(i + 1, end);
        if (cls.startsWith('!')) cls = '^${cls.substring(1)}';
        b.write('[${cls.replaceAll(r'\', r'\\')}]');
        i = end;
      }
    } else {
      b.write(RegExp.escape(c));
    }
  }
  return b.toString();
}

/// Collects the plugin-relative paths of the files to pack under [dir]; a
/// left-out folder is never walked for packing (only counted).
void _walk(Directory dir, String rel, List<_Rule> inherited, List<String> files, Map<String, int> leftOut,
    List<String> links,
    {required Set<String> skip}) {
  final pubignore = File(_join(dir.path, '.pubignore'));
  final gitignore = File(_join(dir.path, '.gitignore'));
  final own = pubignore.existsSync() ? pubignore : (gitignore.existsSync() ? gitignore : null);
  final rules = [...inherited, if (own != null) ..._parseIgnore(own.readAsStringSync(), rel)];
  final entries = dir.listSync(followLinks: false)..sort((a, b) => _name(a.path).compareTo(_name(b.path)));
  for (final entry in entries) {
    final name = _name(entry.path);
    final path = rel.isEmpty ? name : '$rel/$name';
    final isDir = entry is Directory;
    if (skip.contains(_key(entry.path))) continue;
    final lower = name.toLowerCase();
    final builtIn = isDir
        ? _excludedFolders.contains(name) || (rel.isEmpty && _excludedRootFolders.contains(name))
        : _excludedFiles.contains(lower) || _excludedSuffixes.any(lower.endsWith) || _isSecret(lower);
    var ignored = builtIn;
    if (!builtIn) {
      for (final rule in rules) {
        if (rule.matches(path, isDir)) ignored = !rule.negated;
      }
    }
    if (ignored) {
      leftOut[isDir ? '$path/' : path] = isDir ? _countFiles(entry) : 1;
    } else if (entry is Link) {
      links.add(path);
    } else if (isDir) {
      _walk(entry, path, rules, files, leftOut, links, skip: skip);
    } else {
      files.add(path);
    }
  }
}

/// How many files [dir] holds (what could be listed; deep build trees may
/// exceed the Windows path limit).
int _countFiles(Directory dir) {
  var n = 0;
  try {
    for (final e in dir.listSync(recursive: true, followLinks: false)) {
      if (e is File) n++;
    }
  } on FileSystemException {
    // Counted what could be listed.
  }
  return n;
}

/// Why the marketplace would refuse [path], or null.
String? _refusal(String path) {
  if (path.contains(r'\') || path.split('/').contains('..')) return 'unsafe path';
  final name = path.split('/').last;
  final lower = name.toLowerCase();
  if (_allowedDotNames.contains(lower)) return null;
  final dot = name.lastIndexOf('.');
  if (dot <= 0) return _allowedBareNames.contains(lower) ? null : 'no allowed extension';
  final ext = lower.substring(dot + 1);
  return _allowedExtensions.contains(ext) ? null : '.$ext files are not accepted';
}

/// Writes [files] (plugin-relative) under `<top>/` as a zip; returns the
/// unpacked size. Entries are sorted and carry a fixed date, so the same
/// sources give the same bytes.
int _writeZip(File out, Directory root, String top, List<String> files) {
  final raf = out.openSync(mode: FileMode.write);
  final central = BytesBuilder(copy: false);
  var offset = 0;
  var unpacked = 0;
  final deflate = ZLibCodec(raw: true, level: 6);
  try {
    for (final path in files) {
      final data = File(_join(root.path, path)).readAsBytesSync();
      unpacked += data.length;
      final crc = _crc32(data);
      var body = deflate.encode(data);
      var method = 8;
      if (body.length >= data.length) {
        body = data;
        method = 0;
      }
      final nameBytes = utf8.encode('$top/$path');
      if (offset + 30 + nameBytes.length + body.length > 0xFFFFFFFF || files.length > 0xFFFF) {
        throw StateError('the plugin is too large for a zip archive (4 GB, 65535 files)');
      }
      final local = _Le()
        ..u32(0x04034b50)
        ..u16(20)
        ..u16(0x0800) // UTF-8 names
        ..u16(method)
        ..u16(_dosTime)
        ..u16(_dosDate)
        ..u32(crc)
        ..u32(body.length)
        ..u32(data.length)
        ..u16(nameBytes.length)
        ..u16(0)
        ..bytes(nameBytes);
      raf.writeFromSync(local.take());
      raf.writeFromSync(body);
      central.add((_Le()
            ..u32(0x02014b50)
            ..u16(0x0314) // made by: Unix, 2.0
            ..u16(20)
            ..u16(0x0800)
            ..u16(method)
            ..u16(_dosTime)
            ..u16(_dosDate)
            ..u32(crc)
            ..u32(body.length)
            ..u32(data.length)
            ..u16(nameBytes.length)
            ..u16(0)
            ..u16(0)
            ..u16(0)
            ..u16(0)
            ..u32(0x81A40000) // -rw-r--r--
            ..u32(offset)
            ..bytes(nameBytes))
          .take());
      offset += 30 + nameBytes.length + body.length;
    }
    final directory = central.takeBytes();
    raf.writeFromSync(directory);
    raf.writeFromSync((_Le()
          ..u32(0x06054b50)
          ..u16(0)
          ..u16(0)
          ..u16(files.length)
          ..u16(files.length)
          ..u32(directory.length)
          ..u32(offset)
          ..u16(0))
        .take());
  } finally {
    raf.closeSync();
  }
  return unpacked;
}

/// Little-endian byte writer.
class _Le {
  final _b = BytesBuilder();
  void u16(int v) => _b.add([v & 0xFF, (v >> 8) & 0xFF]);
  void u32(int v) => _b.add([v & 0xFF, (v >> 8) & 0xFF, (v >> 16) & 0xFF, (v >> 24) & 0xFF]);
  void bytes(List<int> v) => _b.add(v);
  Uint8List take() => _b.takeBytes();
}

final _crcTable = List<int>.generate(256, (n) {
  var c = n;
  for (var k = 0; k < 8; k++) {
    c = (c & 1) != 0 ? 0xEDB88320 ^ (c >> 1) : c >> 1;
  }
  return c;
});

int _crc32(List<int> data) {
  var c = 0xFFFFFFFF;
  for (final byte in data) {
    c = _crcTable[(c ^ byte) & 0xFF] ^ (c >> 8);
  }
  return c ^ 0xFFFFFFFF;
}

/// [path] made comparable: absolute, `/`-separated, and lower case on Windows.
String _key(String path) {
  final p = File(path).absolute.path.replaceAll(r'\', '/');
  return Platform.isWindows ? p.toLowerCase() : p;
}

/// [path] with the platform's separators.
String _native(String path) => Platform.isWindows ? path.replaceAll('/', r'\') : path;

String _name(String path) => path.split(RegExp(r'[\\/]')).where((s) => s.isNotEmpty).last;

String _join(String dir, String rel) => '$dir${Platform.pathSeparator}${rel.replaceAll('/', Platform.pathSeparator)}';

String _size(int bytes) {
  if (bytes < 1024) return '$bytes B';
  if (bytes < 1024 * 1024) return '${(bytes / 1024).toStringAsFixed(1)} KB';
  return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
}
