// GENERATED BY LUMINA PLUGIN WIZARD (template: importer), then extended into
// the Procedural Content Generation example plugin.
import 'dart:io';

import 'package:lumina_core/lumina_core.dart';
import 'package:lumina_editor_api/lumina_editor_api.dart';
import 'package:shadcn_flutter/shadcn_flutter.dart';

import 'package:lumina_plugin_pcg/src/model/pcg_graph.dart';
import 'package:lumina_plugin_pcg/src/model/pcg_graph_asset.dart';
import 'package:lumina_plugin_pcg/src/ui/pcg_graph_editor.dart';
import 'package:lumina_plugin_pcg/src/ui/pcg_volume_details.dart';
import 'package:lumina_plugin_pcg/src/volume/pcg_volume.dart';
import 'package:lumina_plugin_pcg/src/volume/pcg_volume_service.dart';

/// Procedural Content Generation for Lumina Studio.
///
/// Registers, through `lumina_editor_api` only:
/// - **Plugins → PCG** menu, in three sections: New PCG Graph
///   and Place PCG Volume; Generate All and Cleanup All; About.
/// - the **PCG Graph** asset type (`metadata.custom_type == pcg.graph`) with
///   the form-based [PcgGraphEditor] as its sub-editor;
/// - a **Details** section for `PcgVolume` actors ([PcgVolumeDetails]:
///   graph, seed, size, Generate / Cleanup / Edit Graph);
/// - a `.pcggraph` **importer** (a graph exported as JSON becomes an `.lmas`);
/// - the `pcg.generate` **console command**.
///
/// The level half ([PcgVolumeService]) needs the host's
/// [LuminaEditorHostContext]; under a bare context (a plugin unit test) the
/// contributions still register and the level commands report that there is
/// no level.
class LuminaPluginPcgPlugin extends LuminaEditorPlugin {
  static const String friendlyName = 'Procedural Content Generation';
  static const String version = '0.1.0';

  EditorLevelAccess? _level;
  PcgVolumeService? _service;

  /// The level service, once registered under a host context.
  PcgVolumeService? get service => _service;

  @override
  String get pluginName => 'lumina_plugin_pcg';

  @override
  void register(LuminaEditorContext context) {
    if (context is LuminaEditorHostContext) {
      _level = context.level;
      _service = PcgVolumeService(_level!);
    }

    context.registerMenuItem(
      'Plugins/PCG/New PCG Graph',
      EditorCommand(
        id: 'tools.lumina_plugin_pcg.newGraph',
        label: 'New PCG Graph',
        icon: LucideIcons.workflow,
        canExecute: () => _level != null,
        execute: (ctx) => _newGraph(ctx),
      ),
      options: const EditorMenuItemOptions(section: 'create'),
    );
    context.registerMenuItem(
      'Plugins/PCG/Place PCG Volume',
      EditorCommand(
        id: 'tools.lumina_plugin_pcg.placeVolume',
        label: 'Place PCG Volume',
        icon: LucideIcons.box,
        canExecute: () => _level != null,
        execute: (ctx) => _placeVolume(),
      ),
      options: const EditorMenuItemOptions(section: 'create'),
    );
    context.registerMenuItem(
      'Plugins/PCG/Generate All',
      EditorCommand(
        id: 'tools.lumina_plugin_pcg.generateAll',
        label: 'Generate All',
        icon: LucideIcons.sprout,
        canExecute: () => _level != null,
        execute: (ctx) => _service?.generateAll(),
      ),
      options: const EditorMenuItemOptions(section: 'run'),
    );
    context.registerMenuItem(
      'Plugins/PCG/Cleanup All',
      EditorCommand(
        id: 'tools.lumina_plugin_pcg.cleanupAll',
        label: 'Cleanup All',
        icon: LucideIcons.eraser,
        canExecute: () => _level != null,
        execute: (ctx) => _service?.cleanupAll(),
      ),
      options: const EditorMenuItemOptions(section: 'run'),
    );
    context.registerMenuItem(
      'Plugins/PCG/About $friendlyName',
      EditorCommand(
        id: 'tools.lumina_plugin_pcg.about',
        label: 'About $friendlyName',
        canExecute: () => true,
        execute: (ctx) {
          if (ctx == null) return;
          showOverlay(
            ctx,
            const DialogConfiguration(),
            builder: (c) => AlertDialog(
              title: const Text(friendlyName),
              content: const Text(
                'PCG Graph assets and PCG Volume actors that scatter static meshes over a landscape or a volume floor.'
                '\nVersion: $version',
              ),
              actions: [
                PrimaryButton(onPressed: () => closeOverlay(c), child: const Text('Close')),
              ],
            ),
          );
        },
      ),
      options: const EditorMenuItemOptions(section: 'about'),
    );

    context.registerAssetType(
      EditorAssetTypeHandler(
        customTypeId: PcgGraphAsset.customTypeId,
        displayName: 'PCG Graph',
        icon: LucideIcons.workflow,
        thumbnailBuilder: (_) async => null,
        editorFactory: (ctx, asset) {
          final level = _level;
          if (level == null) return const Center(child: Text('The PCG Graph editor needs the editor level'));
          return PcgGraphEditor(asset: asset, level: level, service: _service!);
        },
      ),
    );

    context.registerDetailsCustomization(
      DetailsCustomization(
        targetTypeId: PcgTypes.volumeActor,
        sectionTitle: 'PCG',
        builder: (ctx, target) {
          final level = _level;
          if (level == null) return const Text('No editor level');
          return PcgVolumeDetails(target: target, level: level, service: _service!);
        },
      ),
    );

    context.registerImporter(
      EditorImporter(
        extensions: const ['.pcggraph'],
        description: 'PCG Graph (JSON) Importer',
        import: (source, ctx) async {
          try {
            final graph = PcgGraph.fromJsonString(await source.readAsString());
            final baseName = source.uri.pathSegments.last.replaceAll('.pcggraph', '');
            final targetPath = '${ctx.targetDirectory}/$baseName.lmas';
            await PcgGraphAsset.save(PcgGraph(name: baseName, nodes: graph.nodes, edges: graph.edges), targetPath);
            return ImportResult.success(targetPath);
          } catch (e) {
            return ImportResult.failure(e.toString());
          }
        },
      ),
    );

    context.registerConsoleCommand('pcg.generate', 'Generate every PCG Volume in the level (pcg.generate [volumeId])', (args) {
      final service = _service;
      if (service == null) return;
      if (args.isEmpty) {
        service.generateAll();
      } else {
        service.generate(args.first);
      }
    });
  }

  @override
  void unregister(LuminaEditorContext context) {
    _level = null;
    _service = null;
  }

  Future<void> _placeVolume() async {
    final service = _service;
    if (service == null) return;
    final graphs = PcgGraphAsset.scan(service.level.projectDirPath);
    await service.placeVolume(location: const [0.0, 0.0, 0.0], graphPath: graphs.isEmpty ? '' : graphs.first);
  }

  /// Creates `contents/pcg/PCG_Graph_<n>.lmas` from the starter graph with
  /// every mesh under `contents/meshes/` as a spawner entry, then opens it.
  Future<void> _newGraph(BuildContext? ctx) async {
    final level = _level;
    if (level == null) return;
    final folder = Directory('${level.projectDirPath}/${PcgGraphAsset.defaultFolder}');
    if (!folder.existsSync()) folder.createSync(recursive: true);
    var n = 1;
    while (File('${folder.path}/PCG_Graph_$n.lmas').existsSync()) {
      n++;
    }
    final name = 'PCG_Graph_$n';
    final meshes = <PcgMeshEntry>[];
    final meshDir = Directory('${level.projectDirPath}/contents/meshes');
    if (meshDir.existsSync()) {
      for (final f in meshDir.listSync(recursive: true, followLinks: false).whereType<File>()) {
        final lower = f.path.toLowerCase();
        if (lower.endsWith('.glb') || lower.endsWith('.gltf') || lower.endsWith('.obj')) {
          meshes.add(PcgMeshEntry(path: PcgGraphAsset.relative(level.projectDirPath, f.path)));
        }
      }
      meshes.sort((a, b) => a.path.compareTo(b.path));
    }
    final relative = '${PcgGraphAsset.defaultFolder}/$name.lmas';
    await PcgGraphAsset.save(PcgGraph.starter(name: name, meshes: meshes), '${level.projectDirPath}/$relative');
    level.log('Created PCG Graph $relative with ${meshes.length} mesh entries', level: 'success', source: PcgVolumeService.logSource);
    level.openAssetEditor(relative);
  }
}

/// Reads a PCG Graph `.lmas` as the host would hand it to the editor
/// (with `metadata.asset_path`): for tests and tools.
LuminaAsset loadPcgGraphAssetForEditor(String absolutePath) {
  final asset = LuminaAsset.fromBytes(File(absolutePath).readAsBytesSync());
  return LuminaAsset(
    assetId: asset.assetId,
    name: asset.name,
    type: asset.type,
    rawPayload: asset.rawPayload,
    metadata: {...asset.metadata, kAssetPathMetadataKey: absolutePath},
  );
}
