import 'package:lumina_editor_api/lumina_editor_api.dart';

/// The actor and component types the PCG plugin places in a level.
abstract final class PcgTypes {
  /// The outliner type of a PCG Volume actor. It carries a [component]
  /// with the graph, seed and size; the game generates it as an empty
  /// scene actor (nothing PCG-specific runs at play time).
  static const String volumeActor = 'PcgVolume';

  /// The component on a PCG Volume that holds its settings.
  static const String component = 'LuminaPcgComponent';

  /// The tag component on every instance a volume generated: `sourceVolume`
  /// names the volume, so Cleanup finds them even after a reparent.
  static const String generatedTag = 'LuminaPcgGeneratedComponent';

  static const String propGraph = 'graphPath';
  static const String propSeed = 'seed';
  static const String propSizeX = 'sizeX';
  static const String propSizeY = 'sizeY';
  static const String propSizeZ = 'sizeZ';
  static const String propInstanceCount = 'instanceCount';
  static const String propSourceVolume = 'sourceVolume';
}

/// A PCG Volume's settings, read from and written to its
/// [PcgTypes.component] properties.
class PcgVolumeSettings {
  /// Project-relative `.lmas` path of the graph, or empty.
  final String graphPath;
  final int seed;

  /// Extents in cm before the actor's scale.
  final double sizeX;
  final double sizeY;
  final double sizeZ;
  final int instanceCount;

  const PcgVolumeSettings({
    this.graphPath = '',
    this.seed = 1,
    this.sizeX = 2000.0,
    this.sizeY = 2000.0,
    this.sizeZ = 500.0,
    this.instanceCount = 0,
  });

  Map<String, dynamic> toProperties() => {
        PcgTypes.propGraph: graphPath,
        PcgTypes.propSeed: seed,
        PcgTypes.propSizeX: sizeX,
        PcgTypes.propSizeY: sizeY,
        PcgTypes.propSizeZ: sizeZ,
        PcgTypes.propInstanceCount: instanceCount,
      };

  factory PcgVolumeSettings.fromProperties(Map<String, dynamic> p) => PcgVolumeSettings(
        graphPath: p[PcgTypes.propGraph] as String? ?? '',
        seed: (p[PcgTypes.propSeed] as num?)?.toInt() ?? 1,
        sizeX: (p[PcgTypes.propSizeX] as num?)?.toDouble() ?? 2000.0,
        sizeY: (p[PcgTypes.propSizeY] as num?)?.toDouble() ?? 2000.0,
        sizeZ: (p[PcgTypes.propSizeZ] as num?)?.toDouble() ?? 500.0,
        instanceCount: (p[PcgTypes.propInstanceCount] as num?)?.toInt() ?? 0,
      );

  /// The settings of [actor], or null when it is not a PCG Volume.
  static PcgVolumeSettings? of(EditorActorSnapshot actor) {
    if (actor.type != PcgTypes.volumeActor) return null;
    final c = actor.componentOfType(PcgTypes.component);
    return PcgVolumeSettings.fromProperties(c?.properties ?? const {});
  }

  /// The spec of a new PCG Volume at [location] (cm, Z up).
  static EditorActorSpec spec({
    required String name,
    required List<double> location,
    String graphPath = '',
    int seed = 1,
    double sizeX = 2000.0,
    double sizeY = 2000.0,
    double sizeZ = 500.0,
  }) =>
      EditorActorSpec(
        name: name,
        type: PcgTypes.volumeActor,
        location: location,
        components: [
          EditorComponentSpec(
            type: PcgTypes.component,
            name: 'PCG Component',
            properties: PcgVolumeSettings(graphPath: graphPath, seed: seed, sizeX: sizeX, sizeY: sizeY, sizeZ: sizeZ).toProperties(),
          ),
        ],
      );

  /// True when [actor] was generated by a PCG Volume ([volumeId] when given).
  static bool isGenerated(EditorActorSnapshot actor, {String? volumeId}) {
    final tag = actor.componentOfType(PcgTypes.generatedTag);
    if (tag == null) return false;
    return volumeId == null || tag.properties[PcgTypes.propSourceVolume] == volumeId;
  }
}
